channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.0
- pip:
  - mlflow==2.15.1
  - cffi==1.17.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - lightgbm==4.5.0
  - matplotlib==3.9.1.post1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==5.9.8
  - pyarrow==15.0.2
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
